name: exam_training
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.2.0
  flutter_slidable: ^1.2.0
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  navigator: ^1.1.0
  provider: ^6.0.2
  modal_bottom_sheet: ^2.0.1
  firebase_auth: ^3.3.13
  flutter_native_splash: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/
